'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dbconectionSQL_GT")>  _
        Public Property dbconectionSQL_GT_Tipo() As String
            Get
                Return CType(Me("dbconectionSQL_GT_Tipo"),String)
            End Get
            Set
                Me("dbconectionSQL_GT_Tipo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EBgpfCZrGOnGgpQ/EvgB55P+sf5JyNqs8NrR1ViH7JubZtNAIAQObulx0fLndAntoLRb5/pMuKTEm58jM"& _ 
            "A7gzdc3rp/9kl1k"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property dbconectionSQL_GT() As String
            Get
                Return CType(Me("dbconectionSQL_GT"),String)
            End Get
            Set
                Me("dbconectionSQL_GT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EBgpfCZrGOnGgpQ/EvgB55P+sf5JyNqsowyNAGRLl+LrEB6cNcuB0ZgVC+9ufVXbBVkaTn5qvjOb6anDI"& _ 
            "TOivA==")>  _
        Public Property dbconectionSQL_GTT() As String
            Get
                Return CType(Me("dbconectionSQL_GTT"),String)
            End Get
            Set
                Me("dbconectionSQL_GTT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EBgpfCZrGOnGgpQ/EvgB55P+sf5JyNqsSeC19hJUa4u7i1PQnCSI5ZgVC+9ufVXbBVkaTn5qvjOb6anDI"& _ 
            "TOivA=="&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property dbconectionSQL_SV() As String
            Get
                Return CType(Me("dbconectionSQL_SV"),String)
            End Get
            Set
                Me("dbconectionSQL_SV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EBgpfCZrGOnGgpQ/EvgB55P+sf5JyNqsuxyl2PsH3Q2YFQvvbn1V2wVZGk5+ar4zm+mpwyEzorw="&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property dbconectionSQL_CR() As String
            Get
                Return CType(Me("dbconectionSQL_CR"),String)
            End Get
            Set
                Me("dbconectionSQL_CR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dbconectionDIAPI_GT")>  _
        Public Property dbconectionDIAPI_GT_Tipo() As String
            Get
                Return CType(Me("dbconectionDIAPI_GT_Tipo"),String)
            End Get
            Set
                Me("dbconectionDIAPI_GT_Tipo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+aUtJuTBXQAiPj7nq6EBPM7kN0BcTg"& _ 
            "5eo6WJFsZZ3maawwl1aRF5EpLE1nhHRTW9q499d15q+nLPjNK87+dfI99yfRp51hVu1OOkKcDP4CXEGN"& _ 
            "m3FDfK/blNqlN4TVFS8sJv5cRBauEvLiDGJqTeALS2eE7kofY5bjhpugW9NmPNrfvekfL9UPWpYEUDaY"& _ 
            "ZL1u/Z18efIDEp0YaM772w91Po=")>  _
        Public Property dbconectionDIAPI_GT() As String
            Get
                Return CType(Me("dbconectionDIAPI_GT"),String)
            End Get
            Set
                Me("dbconectionDIAPI_GT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+aU8gGGETl6mFcKR1Ry3fquqSkC2wC"& _ 
            "Z5N2w2raSrcMAFTsOFU5RaKZI6n87qI3UdKVFx+IBKaeIvN6PpXixfhqgfuHSL7F2DZwm0ygDXdOVoTO"& _ 
            "+WrpPP6Xaxb0gx9zdEsmxR8Kk3FdPoxFoT+iUscZ7769NAoysMpSZCFy1gz/tZjRqaEr89oDlrvAp9Qr"& _ 
            "XnzJQ==")>  _
        Public Property dbconectionDIAPI_GTT() As String
            Get
                Return CType(Me("dbconectionDIAPI_GTT"),String)
            End Get
            Set
                Me("dbconectionDIAPI_GTT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+aQ9QbyBusP34T3iaMc2zsduSkC2wC"& _ 
            "Z5N2w2raSrcMAFTsOFU5RaKZI6n87qI3UdKVFx+IBKaeIvN6PpXixfhqgfuHSL7F2DZwm0ygDXdOVoTO"& _ 
            "+WrpPP6Xaxb0gx9zdEsmxR8Kk3FdPoxFoT+iUscZ7769NAoysMpSZCFy1gz/tZjRqaEr89oDlrvAp9Qr"& _ 
            "XnzJQ==")>  _
        Public Property dbconectionDIAPI_SV() As String
            Get
                Return CType(Me("dbconectionDIAPI_SV"),String)
            End Get
            Set
                Me("dbconectionDIAPI_SV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+aUaVmnPyIYJbkpAtsAmeTdsNq2kq3"& _ 
            "DABU7DhVOUWimSOp/O6iN1HSlRcfiASmniLzej6V4sX4aoH7h0i+xdg2cJtMoA13TlaEzvlq6Tz+l2sW"& _ 
            "9IMfc3RLJsUfCpNxXT6MRaE/olLHGe++vTQKMrDKUmQhctYM/7WY0amhK/PaA5a7wKfUK158yU=")>  _
        Public Property dbconectionDIAPI_CR() As String
            Get
                Return CType(Me("dbconectionDIAPI_CR"),String)
            End Get
            Set
                Me("dbconectionDIAPI_CR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("czepeda")>  _
        Public Property log_Usuario() As String
            Get
                Return CType(Me("log_Usuario"),String)
            End Get
            Set
                Me("log_Usuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Carlos Zepeda")>  _
        Public Property log_Nombre() As String
            Get
                Return CType(Me("log_Nombre"),String)
            End Get
            Set
                Me("log_Nombre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+aU8gGGETl6mFcKR1Ry3fquqSkC2wC"& _ 
            "Z5N2w2raSrcMAFTsOFU5RaKZI6n87qI3UdKVFx+IBKaeIvN6PpXixfhqgfuHSL7F2DZwm0ygDXdOVoTO"& _ 
            "+WrpPP6Xaxb0gx9zdEsmxR8Kk3FdPoxFoT+iUscZ77bQyMJgG2m8lfxkppoUO2k/PrK9I/zIbJkjv17K"& _ 
            "LItCdc3rp/9kl1k")>  _
        Public Property dbconectionDIAPI_GTTGuateplast() As String
            Get
                Return CType(Me("dbconectionDIAPI_GTTGuateplast"),String)
            End Get
            Set
                Me("dbconectionDIAPI_GTTGuateplast") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("informatica@guateplast.com")>  _
        Public Property EMAIL_User() As String
            Get
                Return CType(Me("EMAIL_User"),String)
            End Get
            Set
                Me("EMAIL_User") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inf0gt2015")>  _
        Public Property EMAIL_Password() As String
            Get
                Return CType(Me("EMAIL_Password"),String)
            End Get
            Set
                Me("EMAIL_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SBOGuatetest")>  _
        Public Property log_DB() As String
            Get
                Return CType(Me("log_DB"),String)
            End Get
            Set
                Me("log_DB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EBgpfCZrGOnGgpQ/EvgB55P+sf5JyNqs8NrR1ViH7Js5Zor/pbmLiUtroNDpfiTe7h0i+xdg2cLHlCEH8"& _ 
            "DE3Dw==")>  _
        Public Property dbconectionSQL_MX() As String
            Get
                Return CType(Me("dbconectionSQL_MX"),String)
            End Get
            Set
                Me("dbconectionSQL_MX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FadWnNLdKOTMTlLdf2R2UK+brPZ7tOvlug1xv+1+YMCNolxNs1N+afB+Cn2Wu6ULLqLwyXC5xW77T2AC6"& _ 
            "DA01WBzh5/RqLcMtMW07lMLIbdri/LDFCI96t0mUKp9L2DiSIKjEsLfu1KtaviZ1NC8LmRQf7N12yhg2"& _ 
            "9lZjetxALtC0TRGtM6cm/ReuTew50RGYitrifwbXtAVp1ac0t0o5MxOUt1/ZHZQr5us9nu06+Vh2NuJD"& _ 
            "Q7LioyXfvCEflQE")>  _
        Public Property dbconectionDIAPI_MX() As String
            Get
                Return CType(Me("dbconectionDIAPI_MX"),String)
            End Get
            Set
                Me("dbconectionDIAPI_MX") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GuateSAP;Initial Catalog=SBOGuateplast;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=Plastic0")>  _
        Public ReadOnly Property SBOGuateplastConnectionString() As String
            Get
                Return CType(Me("SBOGuateplastConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GuateSAP;Initial Catalog=APGProduccion;User ID=sa;Password=Plastic0")>  _
        Public ReadOnly Property APGProduccionConnectionString() As String
            Get
                Return CType(Me("APGProduccionConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GuateSAP;Initial Catalog=SBOGuateplast;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=Plastic0")>  _
        Public ReadOnly Property SBOGuateplastConnectionString1() As String
            Get
                Return CType(Me("SBOGuateplastConnectionString1"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.waProduccion_Pedidos.My.MySettings
            Get
                Return Global.waProduccion_Pedidos.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
