Imports DevExpress.XtraReports.UI

Imports System
Imports System.Windows.Forms
Imports System.Drawing.Printing
Imports DevExpress.XtraPrinting
Imports DevExpress.XtraGrid.Dragging
Imports DevExpress.XtraGrid.Columns
Imports System.Reflection
Imports DevExpress.XtraGrid
Imports DevExpress.XtraCharts


Public Class frmControlProduccion

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        'DsdtControlProduccionTableAdapter1.Fill(DsControlProduccion1.dsdtControlProduccion)
    End Sub

    Private Sub frmControlProduccion_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try

            'PRODUCCION PLANIFICADA PROGRAMADOS
            Dim dtOrdenesProgramadas As New DataTable()
            dtOrdenesProgramadas = mConexion.ConectarSQLGT_DT("APGProduccion.dbo.[sp_ProduccionPlanificada]")

            DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Clear()
            If Not dtOrdenesProgramadas.Rows.Count = Nothing Then
                DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Merge(dtOrdenesProgramadas)
            End If

            FC_Chart()
            FC_Chart2()
            ''ARTICULOS PROGRAMADOS
            'Dim dtOrdenesProgramadas As New DataTable()
            'dtOrdenesProgramadas = GET_PlanificacionProduccion_Programada()


            'For I = 0 To dtOrdenesProgramadas.Rows.Count - 1
            '    Dim pHorasPendiente As String = String.Empty
            '    Dim pProduccionHora As String = String.Empty
            '    Dim dtDatosMolde As New DataTable()

            '    pHorasPendiente = mFunciones.FCN_ProduccionHoras(dtOrdenesProgramadas.Rows(I)("CodigoArticulo"), dtOrdenesProgramadas.Rows(I)("Pendiente"))
            '    If Not pHorasPendiente = Nothing Then
            '        dtOrdenesProgramadas.Rows(I)("HorasPendiente") = pHorasPendiente
            '    End If

            '    'dtDatosMolde = mSQLSelect.GET_MoldesProduccionParametros(dtOrdenesProgramadas.Rows(I)("CodigoArticulo"))
            '    dtDatosMolde = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.sp_ProduccionParametros " + dtOrdenesProgramadas.Rows(I)("CodigoArticulo").ToString)

            '    If Not dtDatosMolde.Rows.Count = Nothing Then
            '        pProduccionHora = dtDatosMolde.Rows(0)("ArticulosHora")
            '    End If

            '    If Not pProduccionHora = Nothing Then
            '        dtOrdenesProgramadas.Rows(I)("ProduccionHora") = pProduccionHora
            '    End If
            'Next

            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Clear()
            'If Not dtOrdenesProgramadas.Rows.Count = Nothing Then
            '    DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Merge(dtOrdenesProgramadas)
            'End If

            'FC_Chart()





        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub FC_Chart2()
        ' Create a chart.

        Dim chart2 As ChartControl = ChartControl2

        ' Create an empty Bar series and add it to the chart.
        chart2.Series.Clear() 'limpiar las series
        'CREAR la Serie
        Dim series As New Series("Grupo", ViewType.Bar)
        chart2.Series.Add(series)

        Dim dt As New DataTable()
        dt = mConexion.ConectarSQLGT_DT("APGProduccion.dbo.[sp_HorasDeProduccion_PorGrupo]")

        ' Generate a data table and bind the series to it.
        series.DataSource = dt

        ' Generate a data table and bind the series to it.
        'series.DataSource = DsControlProduccion1.dsdtControlProduccion

        ' Specify data members to bind the series.
        series.ArgumentScaleType = ScaleType.Numerical
        series.ArgumentDataMember = "Grupo"
        series.ValueScaleType = ScaleType.Numerical
        series.ValueDataMembers.AddRange(New String() {"HorasPendiente"})
        series.ToolTipHintDataMember = "Grupo"

        ' Set some properties to get a nice-looking chart.
        CType(series.View, SideBySideBarSeriesView).ColorEach = True
        CType(chart2.Diagram, XYDiagram).AxisY.Visibility = DevExpress.Utils.DefaultBoolean.False
        chart2.Legend.Visibility = DevExpress.Utils.DefaultBoolean.False
        chart2.AnimationStartMode = ChartAnimationMode.OnDataChanged

        'CType(chart2.Diagram, DevExpress.XtraCharts.XYDiagram).Rotated = True

        ' Dock the chart into its parent and add it to the current form.
        chart2.Dock = DockStyle.Fill
        'Me.Controls.Add(chart)

    End Sub
    Private Sub FC_Chart()
        ' Create a chart.

        Dim chart As ChartControl = ChartControl1

        ' Create an empty Bar series and add it to the chart.
        ChartControl1.Series.Clear() 'limpiar las series
        'CREAR la Serie
        Dim series As New Series("Preferencial", ViewType.Bar)
        chart.Series.Add(series)

        Dim dt As New DataTable()
        dt = mConexion.ConectarSQLGT_DT("APGProduccion.dbo.[sp_HorasDeProduccion_PorMaquina]")

        ' Generate a data table and bind the series to it.
        series.DataSource = dt

        ' Generate a data table and bind the series to it.
        'series.DataSource = DsControlProduccion1.dsdtControlProduccion

        ' Specify data members to bind the series.
        series.ArgumentScaleType = ScaleType.Numerical
        series.ArgumentDataMember = "Preferencial"
        series.ValueScaleType = ScaleType.Numerical
        series.ValueDataMembers.AddRange(New String() {"HorasPendiente"})

        ' Set some properties to get a nice-looking chart.
        CType(series.View, SideBySideBarSeriesView).ColorEach = True
        CType(chart.Diagram, XYDiagram).AxisY.Visibility = DevExpress.Utils.DefaultBoolean.False
        chart.Legend.Visibility = DevExpress.Utils.DefaultBoolean.False
        chart.AnimationStartMode = ChartAnimationMode.OnDataChanged

        CType(chart.Diagram, DevExpress.XtraCharts.XYDiagram).Rotated = True

        ' Dock the chart into its parent and add it to the current form.
        chart.Dock = DockStyle.Fill
        'Me.Controls.Add(chart)

    End Sub

    Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs) Handles MyBase.Load
        
    End Sub


    Private Sub tlviewControlProduccion_MouseDown(sender As Object, e As MouseEventArgs) Handles tlviewControlProduccion.MouseDown
        'Try
        '    If e.Button = Windows.Forms.MouseButtons.Right Then
        '        tlviewControlProduccion.Focus()
        '        If tlviewControlProduccion.IsFocusedView Then
        '            If tlviewControlProduccion.FocusedRowHandle > -1 Then
        '                Dim pEstado As String = String.Empty
        '                pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
        '                Dim pPosicion As Integer = Nothing
        '                pPosicion = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "PrioridadMaquina")

        '                Select Case pEstado
        '                    Case "En Proceso"
        '                        rbtnIniciarProceso.Enabled = False
        '                        rbtnDetener.Enabled = True
        '                    Case "En Espera"
        '                        If pPosicion = 1 Then
        '                            rbtnIniciarProceso.Enabled = True
        '                        Else
        '                            rbtnIniciarProceso.Enabled = False
        '                        End If
        '                        rbtnDetener.Enabled = False
        '                    Case "Mantenimiento"
        '                        rbtnIniciarProceso.Enabled = True
        '                        rbtnDetener.Enabled = True

        '                        If pPosicion = 1 Then
        '                            rbtnIniciarProceso.Enabled = True
        '                        Else
        '                            rbtnIniciarProceso.Enabled = False
        '                        End If
        '                End Select
        '            End If
        '        End If

        '        rdlMenu.ShowPopup(MousePosition, True)

        '    End If



        'Catch ex As Exception
        '    mMensajes.msg_Error(ex.Message.ToString)
        'End Try
    End Sub

    Private Sub rbtnIniciarProceso_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles rbtnIniciarProceso.ItemClick
        Try
            tlviewControlProduccion.Focus()
            If tlviewControlProduccion.IsFocusedView Then
                If tlviewControlProduccion.FocusedRowHandle > -1 Then
                    Dim pEstado As String = String.Empty
                    pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
                    Select Case pEstado
                        Case "En Espera"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "En Proceso")
                            FCN_UPDATE_ProgramacionProduccion()
                        Case "Mantenimiento"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "En Proceso")
                            FCN_UPDATE_ProgramacionProduccion()
                    End Select
                End If


                rdlMenu.HidePopup()
                'barbtnIniciarProceso.Enabled = False
                'barbtnDetener.Enabled = True
                'barbtnBajar.Enabled = False
                'barbtnMaquinaCambiar.Enabled = False
            End If

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try

    End Sub
    Private Function FCN_UPDATE_ProgramacionProduccion() As Boolean
        Try
            Dim pCodigoArticulo As String = String.Empty
            Dim pPreferencial As String = String.Empty
            Dim pEstado As String = String.Empty
            Dim pPrioridad As String = String.Empty
            Dim pPrioridadMaquina As String = String.Empty
            Dim pComentarios As String = String.Empty

            pCodigoArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            pPreferencial = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")
            pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
            pPrioridad = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Prioridad")
            pPrioridadMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "PrioridadMaquina")
            pComentarios = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Comentarios")

            If mSQLUpdate.UPDATE_ProgramacionProduccion(pCodigoArticulo, pPreferencial, pEstado, pPrioridad, pPrioridadMaquina, pComentarios) Then
                Return True
            End If

            Return False
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
            Return False
        End Try
    End Function


    Private Sub rbtnDetener_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles rbtnDetener.ItemClick
        Try
            tlviewControlProduccion.Focus()
            If tlviewControlProduccion.IsFocusedView Then
                If tlviewControlProduccion.FocusedRowHandle > -1 Then
                    Dim pEstado As String = String.Empty
                    pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
                    Select Case pEstado
                        Case "En Proceso"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "En Espera")
                            FCN_UPDATE_ProgramacionProduccion()
                        Case "Mantenimiento"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "En Espera")
                            FCN_UPDATE_ProgramacionProduccion()
                    End Select
                End If
            End If

            rdlMenu.HidePopup()
            'rbtnDetener.Enabled = False
            'barbtnIniciarProceso.Enabled = True

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)

        End Try
    End Sub

    Private Sub rbtnMantenimiento_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs)
        Try
            If tlviewControlProduccion.IsFocusedView Then
                If tlviewControlProduccion.FocusedRowHandle > -1 Then
                    Dim pEstado As String = String.Empty
                    pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
                    Select Case pEstado
                        Case "En Proceso"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "Mantenimiento")
                            FCN_UPDATE_ProgramacionProduccion()
                        Case "En Espera"
                            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Estado", "Mantenimiento")
                            FCN_UPDATE_ProgramacionProduccion()
                    End Select
                End If
            End If
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)

        End Try
    End Sub

    Private Sub tlviewControlProduccion_DoubleClick(sender As Object, e As EventArgs) Handles tlviewControlProduccion.DoubleClick
        'frmControlProduccion_Ingreso.ShowDialog()

        'Try
        '    Dim pCodigoArticulo As String = String.Empty
        '    Dim pMaquina As String = String.Empty
        '    pCodigoArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
        '    pMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")

        '    frmControlProduccion_Detalle.Text = "Detalle de Producción Maquina < " + pMaquina + " > Codigo Padre < " + pCodigoArticulo + " >"
        '    frmControlProduccion_Detalle.ppCodigoArticulo = pCodigoArticulo
        '    frmControlProduccion_Detalle.ppMaquina = pMaquina
        '    frmControlProduccion_Detalle.ShowDialog(Me)

        'Catch ex As Exception
        '    mMensajes.msg_Error(ex.Message.ToString)
        'End Try
    End Sub

    Private Sub tlviewControlProduccion_CellValueChanged(sender As Object, e As DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs) Handles tlviewControlProduccion.CellValueChanged
        Try
            FCN_UPDATE_ProgramacionProduccion()
            'FCN_ProgramacionProduccion_Enumerar()

            FC_Chart()
            FC_Chart2()
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub FCN_ProgramacionProduccion_Enumerar()
        Try
            Dim pPrioridadMaquina As Integer = 1
            For i = 0 To DsControlProduccion1.dsdtControlProduccion.Rows.Count - 1

                Dim pMaquinaAnterior As String = String.Empty
                Dim pMaquinaActual As String = String.Empty

                If i = 0 Then
                    pMaquinaAnterior = DsControlProduccion1.dsdtControlProduccion.Rows(Val(i))("Preferencial")
                Else
                    pMaquinaAnterior = DsControlProduccion1.dsdtControlProduccion.Rows(Val(i - 1))("Preferencial")
                End If

                pMaquinaActual = DsControlProduccion1.dsdtControlProduccion.Rows(i)("Preferencial")


                If i = 0 Then
                    pPrioridadMaquina = 1
                Else
                    If pMaquinaActual = pMaquinaAnterior Then
                        pPrioridadMaquina = pPrioridadMaquina + 1
                    Else
                        pPrioridadMaquina = 1
                    End If
                End If

                If i = 0 Then
                    If Not DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina Then
                        DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina
                        mSQLUpdate.UPDATE_ProgramacionProduccion_Prioridad(DsControlProduccion1.dsdtControlProduccion.Rows(i)("CodigoArticulo").ToString, pPrioridadMaquina.ToString)
                    End If
                Else
                    If Not DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina Or Not pMaquinaActual = pMaquinaAnterior Then
                        DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina
                        mSQLUpdate.UPDATE_ProgramacionProduccion_Prioridad(DsControlProduccion1.dsdtControlProduccion.Rows(i)("CodigoArticulo").ToString, pPrioridadMaquina.ToString)
                    End If
                End If


            Next



            'Dim pPrioridadMaquina As Integer = 1
            'For i = 0 To DsControlProduccion1.dsdtControlProduccion.Rows.Count - 1
            '    If i = 0 Then
            '        DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = 1
            '    Else
            '        Dim pMaquinaAnterior As String = String.Empty
            '        Dim pMaquinaActual As String = String.Empty
            '        pMaquinaAnterior = DsControlProduccion1.dsdtControlProduccion.Rows(Val(i - 1))("Preferencial")
            '        pMaquinaActual = DsControlProduccion1.dsdtControlProduccion.Rows(i)("Preferencial")

            '        If pMaquinaActual = pMaquinaAnterior Then
            '            pPrioridadMaquina = pPrioridadMaquina + 1
            '        Else
            '            pPrioridadMaquina = 1
            '        End If
            '        If Not DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina Or Not pMaquinaActual = pMaquinaAnterior Then
            '            DsControlProduccion1.dsdtControlProduccion.Rows(i)("PrioridadMaquina") = pPrioridadMaquina
            '            mSQLUpdate.UPDATE_ProgramacionProduccion_Prioridad(DsControlProduccion1.dsdtControlProduccion.Rows(i)("CodigoArticulo").ToString, pPrioridadMaquina.ToString)
            '        End If
            '    End If
            'Next

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub


    Private Sub barbtnCerrar_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnCerrar.ItemClick
        Try
            Me.Close()
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub tlviewControlProduccion_ItemDrop(sender As Object, e As DevExpress.XtraGrid.Views.Tile.ItemDropEventArgs) Handles tlviewControlProduccion.ItemDrop
        Try

            'MsgBox("ItemDrop")
            'FCN_ProgramacionProduccion_Enumerar() '2018 01 12
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub rbtnEtiquetas_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles rbtnEtiquetas.ItemClick
        Try
            Dim pCodigoPadre As String = String.Empty
            Dim pMaquina As String = String.Empty
            Dim pUbicacion As String = String.Empty
            Dim pUbicacionNombre As String = String.Empty

            pCodigoPadre = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            pMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")

            Dim dtMaquina As New DataTable()
            dtMaquina = GET_Catalogo_Maquinas(pMaquina)

            If Not dtMaquina.Rows.Count = Nothing Then
                pUbicacion = dtMaquina.Rows(0)("Ubicacion").ToString
            End If

            pUbicacion = GET_Listado_MaquinasBodegas(pUbicacion).Rows(0)("Nombre").ToString

            rdlMenu.HidePopup()
            frmEtiquetasSolicitud.Text = "Solicitud de Etiquetas para Maquina " + pMaquina.ToString + " Ubicación " + pUbicacion
            frmEtiquetasSolicitud.vpCodigoPadre = pCodigoPadre
            frmEtiquetasSolicitud.vpMaquina = pMaquina

            frmEtiquetasSolicitud.ShowDialog(Me)
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub


    Private Sub tlviewControlProduccion_EndGrouping(sender As Object, e As EventArgs) Handles tlviewControlProduccion.EndGrouping
        Try
            FCN_ProgramacionProduccion_Enumerar()
        Catch ex As Exception

        End Try
    End Sub

    Private Sub rbtnCambiarMaquina_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles rbtnCambiarMaquina.ItemClick
        Try
            rdlMenu.HidePopup()

            Dim pCodigoArticulo As String = String.Empty
            Dim pNombreArticulo As String = String.Empty
            Dim pMaquina As String = String.Empty
            Dim pId As Integer = 0
            pCodigoArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            pNombreArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "NombreArticulo")
            pMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")
            pId = tlviewControlProduccion.FocusedRowHandle()

            frmTemporal_MaquinasParaTrabajar.ppCodigoPadre = pCodigoArticulo
            frmTemporal_MaquinasParaTrabajar.ppNombre = pNombreArticulo
            frmTemporal_MaquinasParaTrabajar.ShowDialog(Me)

            If frmTemporal_MaquinasParaTrabajar.ppBoolean = False Then
                Exit Sub
            End If
            If Not ssmEsperar.IsSplashFormVisible() Then : ssmEsperar.ShowWaitForm() : End If
            ssmEsperar.SetWaitFormCaption("Esperar")
            ssmEsperar.SetWaitFormDescription("Actualizando!...")


            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "Preferencial", frmTemporal_MaquinasParaTrabajar.ppMaquinaSeleccionada)
            tlviewControlProduccion.SetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "PrioridadMaquina", mSQLSelect.GET_PrioridadMaquina_Siguiente(frmTemporal_MaquinasParaTrabajar.ppMaquinaSeleccionada))

            mSQLUpdate.UPDATE_ProgramacionProduccion(pCodigoArticulo, frmTemporal_MaquinasParaTrabajar.ppMaquinaSeleccionada, frmTemporal_MaquinasParaTrabajar.ppMaquinaSeleccionada - 1)
            frmControlProduccion_Load(sender, e)
            FCN_ProgramacionProduccion_Enumerar()
            tlviewControlProduccion.UpdateCurrentRow()
            tlviewControlProduccion.FocusedRowHandle() = tlviewControlProduccion.LocateByDisplayText(0, colCodigoArticulo, pCodigoArticulo)


            'Dim dt As New DataTable()
            'dt = DsControlProduccion1.dsdtControlProduccion
            'dt.DefaultView.Sort = "Preferencial ASC, PrioridadMaquina ASC"
            'dt = dt.DefaultView.ToTable(True)

            'dt.AcceptChanges()
            'DsControlProduccion1.dsdtControlProduccion.AcceptChanges()

            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Clear()
            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Merge(dt)

            '-----------------------
            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).DefaultView.Sort = "Preferencial ASC, PrioridadMaquina ASC"
            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).DefaultView.ToTable(True)

            'Dim sortedTable = DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).DefaultView.ToTable(True)
            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Clear()
            'DsControlProduccion1.Tables(DsControlProduccion1.dsdtControlProduccion.TableName.ToString).Merge(sortedTable)
            '-----------------------



        Catch ex As Exception
            If ssmEsperar.IsSplashFormVisible() Then : ssmEsperar.CloseWaitForm() : End If
            mMensajes.msg_Error(ex.Message.ToString)
        Finally
            If ssmEsperar.IsSplashFormVisible() Then : ssmEsperar.CloseWaitForm() : End If
        End Try
    End Sub


    Private Sub tlviewControlProduccion_ItemRightClick(sender As Object, e As DevExpress.XtraGrid.Views.Tile.TileViewItemClickEventArgs) Handles tlviewControlProduccion.ItemRightClick
        Try
            'If e.Button = Windows.Forms.MouseButtons.Right Then
            tlviewControlProduccion.Focus()
            If tlviewControlProduccion.IsFocusedView Then
                If tlviewControlProduccion.FocusedRowHandle > -1 Then
                    Dim pEstado As String = String.Empty
                    pEstado = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")
                    Dim pPosicion As Integer = Nothing
                    pPosicion = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "PrioridadMaquina")

                    Select Case pEstado
                        Case "En Proceso"
                            rbtnIniciarProceso.Enabled = False
                            rbtnDetener.Enabled = True
                        Case "En Espera"
                            If pPosicion = 1 Then
                                rbtnIniciarProceso.Enabled = True
                            Else
                                rbtnIniciarProceso.Enabled = False
                            End If
                            rbtnDetener.Enabled = False
                        Case "Mantenimiento"
                            rbtnIniciarProceso.Enabled = True
                            rbtnDetener.Enabled = True

                            If pPosicion = 1 Then
                                rbtnIniciarProceso.Enabled = True
                            Else
                                rbtnIniciarProceso.Enabled = False
                            End If
                    End Select
                End If
            End If
            rdlMenu.ShowPopup(MousePosition, True)
            'End If



        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try

    End Sub

    Private Sub tlviewControlProduccion_ItemDoubleClick(sender As Object, e As DevExpress.XtraGrid.Views.Tile.TileViewItemClickEventArgs) Handles tlviewControlProduccion.ItemDoubleClick
        Try
            Dim pCodigoArticulo As String = String.Empty
            Dim pMaquina As String = String.Empty
            pCodigoArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            pMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")


            frmControlProduccion_Ingreso.Text = "Ingreso de Produccion... Maquina < " + pMaquina + " > Codigo Padre < " + pCodigoArticulo + " >"
            frmControlProduccion_Ingreso.mmCodigo = pCodigoArticulo
            frmControlProduccion_Ingreso.mmMaquina = pMaquina
            frmControlProduccion_Ingreso.ShowDialog(Me)


            'Pendiente de programar
            'frmControlProduccion_Detalle.Text = "Detalle de Producción Maquina < " + pMaquina + " > Codigo Padre < " + pCodigoArticulo + " >"
            'frmControlProduccion_Detalle.ppCodigoArticulo = pCodigoArticulo
            'frmControlProduccion_Detalle.ppMaquina = pMaquina
            'frmControlProduccion_Detalle.ShowDialog(Me)

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    
    Private Sub barbtnProgramacionFinal_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnProgramacionFinal.ItemClick
        Try
            Dim RPTdocumento As DevExpress.XtraReports.UI.XtraReport = New xrptProgramacionProduccionFinal
            RPTdocumento.DataSource = Me.DsControlProduccion1
            RPTdocumento.DataMember = Me.DsControlProduccion1.dsdtControlProduccion.TableName.ToString
            ''dvwReportes.DocumentSource = RPTdocumento
            Dim PrintTool As New ReportPrintTool(RPTdocumento)


            'mFunciones.ExportToPNG(RPTdocumento, "Reporte_ProgramacionProduccionFinal")
            'mSendEmail.FCN_Email_EnviarConAdjuntoDeFondo("Prueba", _
            '                                            "Programacion Produccion Final", _
            '                                            "Detalle de Programacion", _
            '                                            "Reporte_ProgramacionProduccionFinal")

            PrintTool.ShowRibbonPreviewDialog()

        Catch ex As Exception

        End Try
    End Sub

    Private Sub barbtnImprimirGrid_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnImprimirGrid.ItemClick
        Try
            tlviewControlProduccion.ShowRibbonPrintPreview()
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub barbtnExportarXlsx_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnExportarXlsx.ItemClick
        Try
            sfdSave.Filter = "Archivos Excel | *.xlsx"
            If sfdSave.ShowDialog(Me) = Windows.Forms.DialogResult.OK Then
                tlviewControlProduccion.ExportToXlsx(sfdSave.FileName)
            End If
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub barbtnProgramacionGrafica_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnProgramacionGrafica.ItemClick
        Try
            frmTemporal_ProgramacionGrafica.ShowDialog(Me)
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub frmControlProduccion_HelpButtonClicked(sender As Object, e As System.ComponentModel.CancelEventArgs) Handles MyBase.HelpButtonClicked
        mMensajes.msg_Error("Prueba de Help")
    End Sub
    Private Sub tlviewControlProduccion_ItemPress(sender As Object, e As DevExpress.XtraGrid.Views.Tile.TileViewItemClickEventArgs) Handles tlviewControlProduccion.ItemPress
        Try
            'Dim pPrioridad As String = String.Empty
            'Dim pStatus As String = String.Empty

            'pPrioridad = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "PrioridadMaquina")
            'pStatus = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")

            'If pPrioridad = 1 And pStatus = "En Proceso" Then
            '    tlviewControlProduccion.OptionsDragDrop.AllowDrag = False
            'Else
            '    tlviewControlProduccion.OptionsDragDrop.AllowDrag = True
            'End If



        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try


    End Sub
    Private Sub tlviewControlProduccion_FocusedRowObjectChanged(sender As Object, e As DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs) Handles tlviewControlProduccion.FocusedRowObjectChanged

        'Dim pi As PropertyInfo = TypeOf(tlviewControlProduccion).get
        'Dim dc As DragController
        'dc = pi.

        'dc.CancelDrag()


        'Dim pPrioridad As String = String.Empty
        'Dim pStatus As String = String.Empty

        'pPrioridad = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "PrioridadMaquina")
        'pStatus = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Estado")

        'If pPrioridad = 1 And pStatus = "En Proceso" Then

        'Else
        '    tlviewControlProduccion.OptionsDragDrop.AllowDrag = True
        'End If


        'mMensajes.msg_Error(e.FocusedRowHandle.ToString + "FocusedRowObjectChanged" + e.RowHandle.ToString)
    End Sub

    Private Sub grdControlProduccion_QueryContinueDrag(sender As Object, e As QueryContinueDragEventArgs) Handles grdControlProduccion.QueryContinueDrag
        e.Action = DragAction.Cancel
    End Sub

    Private Sub tlviewControlProduccion_ItemClick(sender As Object, e As Views.Tile.TileViewItemClickEventArgs) Handles tlviewControlProduccion.ItemClick
        Try
            Fill_Colores()

            'OBTENER CODIGO DE ARTICULO
            Dim pCodigo As String = String.Empty
            pCodigo = tlviewControlProduccion.GetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "CodigoArticulo")


            If Not Sub_Fill_Molde(pCodigo) Then : mMensajes.msg_Informacion("No existen parametros de Molde.") : End If
            If Not Sub_Fill_Produccion_Paremetros(pCodigo) Then : mMensajes.msg_Informacion("No existen parametros de Produccion.") : End If

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub tlviewControlProduccion_FocusedRowChanged(sender As Object, e As Views.Base.FocusedRowChangedEventArgs) Handles tlviewControlProduccion.FocusedRowChanged
        Try
            'OBTENER CODIGO DE ARTICULO
            Dim pCodigo As String = String.Empty
            pCodigo = tlviewControlProduccion.GetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "CodigoArticulo")

            Fill_Colores()
            If Not Sub_Fill_Molde(pCodigo) Then : mMensajes.msg_Informacion("No existen parametros de Molde.") : End If
            If Not Sub_Fill_Produccion_Paremetros(pCodigo) Then : mMensajes.msg_Informacion("No existen parametros de Produccion.") : End If

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub Fill_Colores()
        Try
            Dim pCodigo As String = String.Empty
            pCodigo = tlviewControlProduccion.GetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "CodigoArticulo")

            Dim dtColores As New DataTable()
            dtColores = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.[Ensamble_Ordenes_Hijos] CP," + pCodigo.ToString)

            'COLORES - Limpiar Controles
            DsControlProduccion1.Tables(DsControlProduccion1.dsdtColores.TableName.ToString).Clear()
            txtCodigoPadre.EditValue = Nothing

            'COLORES - Llenar Controles
            If Not dtColores.Rows.Count = Nothing Then
                txtCodigoPadre.EditValue = dtColores.Rows(0)("CodigoPadre")
                'LLENA LA TABLA DE COLORES
                DsControlProduccion1.Tables(DsControlProduccion1.dsdtColores.TableName.ToString).Merge(dtColores)
            End If


        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub


    Private Function Sub_Fill_Molde(ByVal pCodigo As String) As Boolean
        Try
            Dim dtMoldes As New DataTable("CodigosProducidosMoldes")
            dtMoldes = GET_Listado_CodigosProducidos(pCodigo)
            If dtMoldes.Rows.Count = Nothing Then
                Return False
            End If

            Dim dt As New DataTable("dtMaquinas")
            dt = mSQLSelect.GET_MoldesMaquinasParametros(dtMoldes.Rows(0)("Molde").ToString)

            txtMolde.EditValue = String.Empty
            txtNombre.EditValue = String.Empty
            txtCavidades.EditValue = String.Empty
            txtunidades.EditValue = String.Empty
            txtLugar.EditValue = String.Empty
            txtUbicacion.EditValue = String.Empty
            txtPreferencial.EditValue = String.Empty

            If dt.Rows.Count = Nothing Then
                Return False
            End If

            txtMolde.EditValue = dt.Rows(0)("Id").ToString
            txtNombre.EditValue = dt.Rows(0)("Nombre").ToString
            txtCavidades.EditValue = dt.Rows(0)("Cavidades").ToString
            txtunidades.EditValue = dt.Rows(0)("Unidades").ToString
            txtLugar.EditValue = dt.Rows(0)("Bodega").ToString
            txtUbicacion.EditValue = dt.Rows(0)("Ubicacion").ToString
            txtPreferencial.EditValue = dt.Rows(0)("MaquinaPreferencial").ToString

            Return True

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
            Return False
        End Try
    End Function
    Private Function Sub_Fill_Produccion_Paremetros(ByVal pCodigo As String) As Boolean
        Try
            Dim dt As New DataTable("dtMaquinas")
            dt = mSQLSelect.GET_MoldesProduccionParametros(pCodigo)

            txtCiclo.EditValue = String.Empty
            txtCicloHora.EditValue = String.Empty
            txtCicloTurno.EditValue = String.Empty
            txtCicloMinimo.EditValue = String.Empty
            txtCicloMaximo.EditValue = String.Empty

            txtInyeccion.EditValue = String.Empty
            txtInyeccionMinima.EditValue = String.Empty
            txtInyeccionMaxima.EditValue = String.Empty
            txtLibrasHora.EditValue = String.Empty
            txtSacosDia.EditValue = String.Empty
            'txtHorasReq.EditValue = String.Empty
            'txtTurnosReq.EditValue = String.Empty

            If dt.Rows.Count = Nothing Then
                Return False
            Else
                If dt.Rows(0)("ArticulosHora").ToString = "0.0" Then
                    Return False
                End If
            End If

            txtCiclo.EditValue = dt.Rows(0)("Ciclo").ToString
            txtCicloHora.EditValue = dt.Rows(0)("CicloHora").ToString
            txtCicloTurno.EditValue = dt.Rows(0)("CicloTurno").ToString
            txtCicloMinimo.EditValue = dt.Rows(0)("CicloMin").ToString
            txtCicloMaximo.EditValue = dt.Rows(0)("CicloMax").ToString
            txtInyeccion.EditValue = dt.Rows(0)("PesoInyeccionGrms").ToString
            txtInyeccionMinima.EditValue = dt.Rows(0)("RangoPesoGrmsMin").ToString
            txtInyeccionMaxima.EditValue = dt.Rows(0)("RangoPesoGrmsMax").ToString
            txtLibrasHora.EditValue = dt.Rows(0)("LbHora").ToString
            txtSacosDia.EditValue = dt.Rows(0)("Sacos25KG").ToString


            'Dim pCantidad As Decimal = "0.00"
            'pCantidad = colProdFinal.SummaryItem.SummaryValue

            'If Not txtCicloHora.EditValue = String.Empty Then
            '    pCantidad = Val(pCantidad) / Val(txtCicloHora.EditValue)
            '    txtHorasReq.EditValue = Math.Ceiling(pCantidad)
            '    'txtTurnosReq.EditValue = pCantidad / 12))
            '    txtTurnosReq.EditValue = Format(Val(pCantidad / 12), "0.0")
            'End If

            'txtTurnosReq.EditValue = String.Empty

            Return True
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
            Return False
        End Try
    End Function

    'Private Function Sub_Fill_ComponentesProducidos() As Boolean
    '    Try
    '        'Dim dt As New DataTable("dtMaquinas")
    '        'dt = mSQLSelect.GET_Listado_CodigosProducidos(vpCodigoArticulo)

    '        'If dt.Rows.Count = Nothing Then
    '        '    Return False
    '        'End If

    '        'txtMaterial1.EditValue = dt.Rows(0)("Material1").ToString
    '        'txtMaterial1Porc.EditValue = dt.Rows(0)("Material1Porc").ToString
    '        'txtMaterial2.EditValue = dt.Rows(0)("Material2").ToString
    '        'txtMaterial2Porc.EditValue = dt.Rows(0)("Material2Porc").ToString
    '        'txtMaterial3.EditValue = dt.Rows(0)("Material3").ToString
    '        'Return True


    '        'PARAMETROS DE MATERIALES
    '        Dim dtMateriales As New DataTable("dt")
    '        dtMateriales = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.Material_Porcentaje '" + vpCodigoArticulo + "'")
    '        If Not dtMateriales.Rows.Count = Nothing Then

    '            txtMaterial1.EditValue = dtMateriales.Rows(0)("Codigo").ToString
    '            txtMaterial1Porc.EditValue = dtMateriales.Rows(0)("Porcentaje").ToString

    '            If dtMateriales.Rows.Count = 2 Then
    '                txtMaterial2.EditValue = dtMateriales.Rows(1)("Codigo").ToString
    '                txtMaterial2Porc.EditValue = dtMateriales.Rows(1)("Porcentaje").ToString
    '            Else
    '                txtMaterial2.EditValue = String.Empty
    '                txtMaterial2Porc.EditValue = Nothing
    '            End If

    '            If dtMateriales.Rows.Count = 3 Then
    '                txtMaterial3.EditValue = dtMateriales.Rows(2)("Codigo").ToString
    '                'txtMaterial3.EditValue = dtMateriales.Rows(2)("Porcentaje").ToString
    '            Else
    '                txtMaterial3.EditValue = String.Empty
    '                'txtMaterial3Porc.EditValue = Nothing
    '            End If

    '            Return True
    '        Else
    '            Return False
    '        End If




    '    Catch ex As Exception
    '        mMensajes.msg_Error(ex.Message.ToString)
    '        Return False
    '    End Try
    'End Function
    'Private Function Sub_Fill_Maquinas() As Boolean
    '    Try
    '        Dim dtMoldes As New DataTable("CodigosProducidosMoldes")
    '        dtMoldes = GET_Listado_CodigosProducidos(vpCodigoArticulo)
    '        If dtMoldes.Rows.Count = Nothing Then
    '            Return False
    '        End If

    '        Dim dt As New DataTable("dtMaquinas")
    '        dt = mSQLSelect.GET_MoldesMaquinasTrabajar(dtMoldes.Rows(0)("Molde").ToString)

    '        DsOrdenProduccionImpresion.Tables(DsOrdenProduccionImpresion.dsdtMoldesMaquinasTrabajar.TableName.ToString).Clear()

    '        If dt.Rows.Count = Nothing Then
    '            Return False
    '        End If

    '        DsOrdenProduccionImpresion.Tables(DsOrdenProduccionImpresion.dsdtMoldesMaquinasTrabajar.TableName.ToString).Merge(dt)
    '        Return True
    '    Catch ex As Exception
    '        mMensajes.msg_Error(ex.Message.ToString)
    '        Return False
    '    End Try
    'End Function
    
    




    Private Sub barbtnRecibo_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnRecibo.ItemClick
        Try
            frmReciboProduccionEnsamble.Text = "Recibos de Produccion y Ensamble"
            frmReciboProduccionEnsamble.StartPosition = FormStartPosition.CenterScreen
            frmReciboProduccionEnsamble.vpCodigoArticulo = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            frmReciboProduccionEnsamble.ShowDialog()

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub barbtnSolicitarEtiquetas_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnSolicitarEtiquetas.ItemClick
        Try
            Dim pCodigoPadre As String = String.Empty
            Dim pMaquina As String = String.Empty
            Dim pUbicacion As String = String.Empty
            Dim pUbicacionNombre As String = String.Empty

            pCodigoPadre = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "CodigoArticulo")
            pMaquina = mFunciones.FCN_GetCellValue(tlviewControlProduccion, "Preferencial")

            Dim dtMaquina As New DataTable()
            dtMaquina = GET_Catalogo_Maquinas(pMaquina)

            If Not dtMaquina.Rows.Count = Nothing Then
                pUbicacion = dtMaquina.Rows(0)("Ubicacion").ToString
            End If

            pUbicacion = GET_Listado_MaquinasBodegas(pUbicacion).Rows(0)("Nombre").ToString

            'rdlMenu.HidePopup()
            frmEtiquetasSolicitud.Text = "Solicitud de Etiquetas para Maquina " + pMaquina.ToString + " Ubicación " + pUbicacion
            frmEtiquetasSolicitud.vpCodigoPadre = pCodigoPadre
            frmEtiquetasSolicitud.vpMaquina = pMaquina

            frmEtiquetasSolicitud.ShowDialog(Me)
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

   
    Private Sub barbtnEditarTrabajos_DownChanged(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnEditarTrabajos.DownChanged
        Try
            If barbtnEditarTrabajos.Down = True Then
                tlviewControlProduccion.OptionsDragDrop.AllowDrag = True
            Else
                tlviewControlProduccion.OptionsDragDrop.AllowDrag = False
            End If

        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub

    Private Sub barbtnInstruccionesTrabajo_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles barbtnInstruccionesTrabajo.ItemClick

        Try


            '--------------------------------------------------------------------------------------------------------------------------
            ' PARAMETROS DE ARTICULO
            Dim pCodigo As String = String.Empty
            pCodigo = tlviewControlProduccion.GetRowCellValue(tlviewControlProduccion.FocusedRowHandle, "CodigoArticulo")

            If pCodigo = Nothing Then
                mMensajes.msg_Error("Ingrese un codigo Válido...")
            End If


            '--------------------------------------------------------------------------------------------------------------------------
            'FILL DATOS DEL ARTICULO
            Dim dtOITM As New DataTable()
            dtOITM = mSQLSelect.GET_Procedimientos_OITM(pCodigo)

            'DELETE OITM
            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_OITM.TableName.ToString).Clear()

            'FILL OITM
            If Not dtOITM.Rows.Count = Nothing Then
                DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_OITM.TableName.ToString).Merge(dtOITM)
            End If

            '--------------------------------------------------------------------------------------------------------------------------
            'FILL ADVERTENCIAS DE TRABAJO
            Dim dtAdvertencias As New DataTable()
            dtAdvertencias = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.[Advertencias_Parametros] '" + pCodigo + "'")

            'DELETE ADVERTENCIAS
            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Advertencias.TableName.ToString).Clear()

            'FILL ADVERTENCIAS
            If Not dtAdvertencias.Rows.Count = Nothing Then
                DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Advertencias.TableName.ToString).Merge(dtAdvertencias)
            End If

            '--------------------------------------------------------------------------------------------------------------------------
            'FILL INSTRUCCIONES DE TRABAJO

            Dim dtInstrucciones As New DataTable()

            dtInstrucciones = mSQLSelect.GET_InstruccionesTrabajo(pCodigo)

            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Instrucciones.TableName.ToString).Clear()

            If Not dtInstrucciones.Rows.Count = Nothing Then
                DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Instrucciones.TableName.ToString).Merge(dtInstrucciones)
            End If

            '--------------------------------------------------------------------------------------------------------------------------
            'FILL PARAMETROS DE EMPAQUE

            Dim dtEmpaque As New DataTable()
            dtEmpaque = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.Empaque_Parametros '" + pCodigo + "'")

            'DELETE EMAPQUE
            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Empaque.TableName.ToString).Clear()

            'FILL EMPAQUE
            If Not dtEmpaque.Rows.Count = Nothing Then
                DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Empaque.TableName.ToString).Merge(dtEmpaque)
            End If

            '--------------------------------------------------------------------------------------------------------------------------
            'FILL PARAMETROS DE EMPAQUE FORMA 2

            Dim dtEmpaque2 As New DataTable()
            dtEmpaque2 = mConexion.ConectarSQLGT_DT("EXEC APGProduccion.dbo.Empaque_Parametros_XId '" + pCodigo + "'")

            'BORRAR DATASET
            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Empaque_Forma2.TableName.ToString).Clear()

            'LLENAR DATASET
            If Not dtEmpaque.Rows.Count = Nothing Then
                DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_Empaque_Forma2.TableName.ToString).Merge(dtEmpaque2)
            End If

            '--------------------------------------------------------------------------------------------------------------------------
            'FILL PATH DE FOTOGRAFIAS DE INSTRUCCIONES DE TRABAJO

            'OBTENER PATH PARA BUSQUEDA DE FOTOGRAFIAS DE INSTRUCCIONES DE TRABAJO
            Dim dtPath As New DataTable()
            Dim pPath As String = String.Empty

            dtPath = mSQLSelect.GET_Listado("Directorio_InstruccionesTrabajo")
            If Not dtPath.Rows.Count = Nothing Then
                pPath = dtPath.Rows(0)("Descripcion").ToString
            End If


            'CREACION DE TABLA PARA GUARDAR DIRECTORIOS DE COINCIDENCIAS DE FOTOGRAFIAS
            Dim dt As New DataTable()
            dt.Columns.Add("Path", GetType(String))

            For Each foundFile As String In My.Computer.FileSystem.GetFiles(
             pPath, FileIO.SearchOption.SearchAllSubDirectories, "" + pCodigo + "*")

                dt.Rows.Add(foundFile.ToString)
            Next

            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_FotoInstruccionesTrabajo.TableName.ToString).Clear()
            DsParametros_Instrucciones1.Tables(DsParametros_Instrucciones1.dsdtImpresion_FotoInstruccionesTrabajo.TableName.ToString).Merge(dt)


            '--------------------------------------------------------------------------------------------------------------------------
            'REPORTE

            Dim RPTdocumento As DevExpress.XtraReports.UI.XtraReport = New xrptParametros_AdvertenciasTrabajo
            RPTdocumento.DataSource = Me.DsParametros_Instrucciones1
            RPTdocumento.DataMember = DsParametros_Instrucciones1.dsdtImpresion_Encabezado.TableName.ToString
            RPTdocumento.RequestParameters = False

            'Dim RPTdocumento2 As DevExpress.XtraReports.UI.XtraReport = New xrptParametros_InstruccionesTrabajo
            'RPTdocumento2.DataSource = Me.DsParametros_Instrucciones1
            'RPTdocumento2.DataMember = DsParametros_Instrucciones1.dsdtImpresion_Instrucciones.TableName.ToString
            'RPTdocumento2.RequestParameters = False

            'RPTdocumento2.Parameters("pCodigo").Value = pCodigo
            'RPTdocumento2.Parameters("pInstruccionesTrabajo").Value = mmeInstruccionTrabajo.EditValue

            'RPTdocumento2.CreateDocument()

            Dim PrintTool As New ReportPrintTool(RPTdocumento)
            PrintTool.ShowRibbonPreviewDialog()
        Catch ex As Exception
            mMensajes.msg_Error(ex.Message.ToString)
        End Try
    End Sub


End Class